import { postBodies } from "./fallback-rich.ts";
import type { Bike, Post, Product, Service, Testimonial } from "./types";

/**
 * Content lifted verbatim from the approved design (design/assets/js/data.js).
 * Used whenever Sanity is not configured or is unreachable, so the site
 * renders pixel-perfect out of the box. The Sanity seed (../studio/seed.ndjson)
 * is generated from this same content — see scripts/generate-seed.mjs.
 */

export const fallbackServices: Service[] = [
  {
    slug: "engine-repairs",
    order: 1,
    num: "01",
    title: "Engine Repairs",
    icon: "cog",
    description: "Top-end rebuilds, full bottom-end overhauls and cylinder work for inline-4, V-twin and parallel-twin engines.",
  },
  {
    slug: "performance-tuning",
    order: 2,
    num: "02",
    title: "Performance Tuning",
    icon: "gauge",
    description: "Dyno-backed fuel/ignition mapping, exhaust upgrades and intake work to unlock the engine's real potential.",
  },
  {
    slug: "ecu-diagnostics",
    order: 3,
    num: "03",
    title: "ECU Diagnostics",
    icon: "cpu",
    description: "OBD-II and OEM-grade tools for BMW, Ducati, Yamaha, Honda, KTM and Kawasaki. Fault codes, live data, recalibration.",
  },
  {
    slug: "suspension-brakes",
    order: 4,
    num: "04",
    title: "Suspension & Brakes",
    icon: "suspension",
    description: "Fork rebuilds, shock servicing, sag setup, brake bleeding, master-cylinder and caliper restoration.",
  },
  {
    slug: "custom-modifications",
    order: 5,
    num: "05",
    title: "Custom Modifications",
    icon: "wrench",
    description: "Tail tidies, fairing work, exhaust fabrication, café racer and supermoto conversions — built clean, built to ride.",
  },
  {
    slug: "oil-maintenance",
    order: 6,
    num: "06",
    title: "Oil & Maintenance",
    icon: "droplet",
    description: "Genuine Motul, Castrol and Mobil1 oils. Filter changes, coolant flushes, full A-class service intervals.",
  },
  {
    slug: "accident-repairs",
    order: 7,
    num: "07",
    title: "Accident Repairs",
    icon: "alert",
    description: "Frame straightening, fairing replacement and full cosmetic restoration. Insurance-friendly documentation.",
  },
  {
    slug: "tire-chain",
    order: 8,
    num: "08",
    title: "Tire & Chain",
    icon: "disc",
    description: "Pirelli, Michelin and Metzeler fitment with proper balancing. DID and EK chain replacement with sprocket service.",
  },
];

export const fallbackBikes: Bike[] = [
  {
    slug: "s1000rr-m-sport-2023",
    order: 1,
    model: "S1000RR M-Sport",
    brand: "BMW",
    type: "Superbike",
    year: 2023,
    engineCc: 999,
    mileageKm: 4200,
    price: 8950000,
    status: "available",
    registered: true,
    registrationNumber: "CBN-XXXX",
    badge: "Featured",
    colour: "Light White / M-Motorsport",
    power: "207 hp @ 13,500 rpm",
    torque: "113 Nm @ 11,000 rpm",
    weight: "197 kg",
    transmission: "6-speed quickshifter",
    description: "An immaculate single-owner M-Sport spec S1000RR with full BMW service history. ShiftCam variable valve timing, M Endurance chain, and the Race Pro electronics package mean this bike is as track-ready as it is road-livable.",
    features: ["Full M-Sport spec", "Race Pro modes", "Quickshifter Pro (up/down)", "Cornering ABS Pro", "M lightweight battery", "M Carbon wheels", "Akrapovič slip-on", "Pirelli Diablo Supercorsa SP V3"],
    gallery: ["/img/cbr1000rr-front.jpg", "/img/silver-r1.jpg", "/img/diagnostic-work.jpg"],
    featured: true,
  },
  {
    slug: "hypermotard-821-2014",
    order: 2,
    model: "Hypermotard 821",
    brand: "Ducati",
    type: "Supermoto",
    year: 2014,
    engineCc: 821,
    mileageKm: 18500,
    price: 4250000,
    status: "available",
    registered: true,
    registrationNumber: "BFK-XXXX",
    badge: "Just In",
    colour: "Ducati Red",
    power: "110 hp @ 9,250 rpm",
    torque: "89 Nm @ 7,750 rpm",
    weight: "204 kg",
    transmission: "6-speed",
    description: "A clean 821 Hypermotard with proper desmo service history (we did the last one). Termignoni full system fitted, Öhlins steering damper, and a handlebar swap to flat MX bars. Wheelies at will.",
    features: ["Termignoni full exhaust system", "Öhlins steering damper", "Renthal Fatbar", "Pirelli Diablo Rosso III", "Desmo valve service current", "New chain & sprocket set"],
    gallery: ["/img/ducati-hyper.jpg", "/img/red-supermoto.jpg"],
    featured: true,
  },
  {
    slug: "yzf-r1-2024",
    order: 3,
    model: "YZF-R1",
    brand: "Yamaha",
    type: "Superbike",
    year: 2024,
    engineCc: 998,
    mileageKm: 1100,
    price: 9750000,
    status: "available",
    registered: false,
    badge: "Low KM",
    colour: "Icon Performance Silver",
    power: "200 hp @ 13,500 rpm",
    torque: "112 Nm @ 11,500 rpm",
    weight: "201 kg",
    transmission: "6-speed seamless",
    description: "Brand-new condition R1 with crossplane crank and Yamaha's latest electronics. Sold unregistered — buyer handles registration. Ideal for those wanting track-day-first ownership.",
    features: ["Crossplane CP4 engine", "Slide control system", "Launch control", "Quickshifter (up/down)", "Magnesium subframe", "KYB inverted forks", "Brembo monobloc front", "Bridgestone RS11"],
    gallery: ["/img/silver-r1.jpg", "/img/cbr1000rr-front.jpg"],
    featured: true,
  },
  {
    slug: "1290-super-duke-r-2022",
    order: 4,
    model: "1290 Super Duke R",
    brand: "KTM",
    type: "Naked",
    year: 2022,
    engineCc: 1301,
    mileageKm: 7800,
    price: 7400000,
    status: "available",
    registered: true,
    registrationNumber: "CAJ-XXXX",
    colour: "Orange / Black",
    power: "180 hp @ 9,500 rpm",
    torque: "140 Nm @ 8,000 rpm",
    weight: "189 kg",
    transmission: "6-speed PASC",
    description: "The Beast 3.0. Massive 1301cc V-twin, Brembo Stylema brakes, WP Apex semi-active suspension. We've serviced it from new — every receipt, every photo.",
    features: ["WP Apex semi-active suspension", "Brembo Stylema calipers", "Cornering MTC + ABS", "Quickshifter+", "Akrapovič slip-on", "Power Parts seat upgrade"],
    gallery: ["/img/red-supermoto.jpg", "/img/ducati-hyper.jpg"],
  },
  {
    slug: "ftr-223-2019",
    order: 5,
    model: "FTR 223",
    brand: "Honda",
    type: "Scrambler",
    year: 2019,
    engineCc: 223,
    mileageKm: 22000,
    price: 1450000,
    status: "available",
    registered: true,
    registrationNumber: "PA-XXXX",
    badge: "Garage Pick",
    colour: "Pearl Orange",
    power: "16 hp @ 7,500 rpm",
    torque: "17 Nm @ 6,000 rpm",
    weight: "121 kg",
    transmission: "5-speed",
    description: "Honda FTR 223 — the cult-classic flat-tracker styled commuter. Reliable air-cooled single, easy to ride, easy to live with. Recent top-end refresh and full tune-up.",
    features: ["Recent top-end service", "New chain + sprockets", "New tires", "Aftermarket exhaust", "LED lighting upgrade"],
    gallery: ["/img/d-tracker-orange.jpg", "/img/yellow-wr.jpg"],
  },
  {
    slug: "wr-155-r-2023",
    order: 6,
    model: "WR 155 R",
    brand: "Yamaha",
    type: "Enduro",
    year: 2023,
    engineCc: 155,
    mileageKm: 5400,
    price: 1690000,
    status: "available",
    registered: false,
    colour: "Racing Blue",
    power: "16 hp @ 10,000 rpm",
    torque: "14 Nm @ 8,500 rpm",
    weight: "134 kg",
    transmission: "6-speed",
    description: "Yamaha WR 155 R fresh-import unit. VVA engine, long-travel suspension, ready to be registered and ridden. Perfect for the rider who wants on/off-road versatility.",
    features: ["VVA variable valve actuation", "Long-travel KYB suspension", "Disc brakes front & rear", "Digital instrument cluster", "Underseat storage", "37mm USD forks"],
    gallery: ["/img/blue-wr-twins.jpg", "/img/yellow-wr.jpg", "/img/d-tracker-blue.jpg"],
  },
];

export const fallbackProducts: Product[] = [
  {
    slug: "arai-rx-7v-evo",
    order: 1,
    title: "Arai RX-7V Evo",
    category: "Helmets",
    icon: "helmet",
    brand: "Arai",
    shortDescription: "Top-tier FIM-homologated racing lid. Aramid + carbon shell. Multiple colorways available on order.",
    description: "The Arai RX-7V Evo is what MotoGP riders use when they can. PB-cLc 2 shell construction (Peripherally Belted Complex Laminate Construction) is hand-laid by master technicians in Japan. R75 shape philosophy gives unmatched impact deflection. Comes with the new VAS Max Flow ventilation system and emergency removable cheek pads.",
    features: ["FIM-homologated", "PB-cLc 2 shell", "VAS Max Flow ventilation", "Emergency Release System (ERS) cheek pads", "Pinlock-ready visor", "Multiple shell sizes (XS–XXL)"],
    price: 245000,
    sku: "AR-RX7V-EVO",
    tag: "PREMIUM",
    inStock: true,
    featured: true,
  },
  {
    slug: "pirelli-diablo-rosso-iv",
    order: 2,
    title: "Pirelli Diablo Rosso IV",
    category: "Tires",
    icon: "tire",
    brand: "Pirelli",
    shortDescription: "Hyper-sport tire built for road and track. Available in front and rear sizing for most superbikes.",
    description: "The Diablo Rosso IV is the road-going descendant of the Supercorsa. Tri-compound rear with hard centre for mileage, soft shoulders for grip. Bi-compound front. Race-derived profile from SBK. Performs in dry, surprises in wet.",
    features: ["Tri-compound rear / bi-compound front", "Race-derived profile", "Available in 120/70-17 front, 180/55-17 / 190/55-17 rear", "Heat-up time under 2 km", "Approx 8,000 km tread life", "Wet performance certified"],
    price: 78500,
    sku: "PI-DR4-180",
    tag: "TIRE",
    inStock: true,
    featured: true,
  },
  {
    slug: "hlins-ttx-rear-shock",
    order: 3,
    title: "Öhlins TTX Rear Shock",
    category: "Suspension",
    icon: "shock",
    brand: "Öhlins",
    shortDescription: "Twin-tube rear shock. Independently adjustable compression and rebound. Track-grade damping.",
    description: "The TTX (Twin-Tube Technology) eliminates cavitation and provides consistent damping at any temperature. Used by MotoGP and WSBK teams. Adjustments for compression, rebound, preload and length — calibrated for your bike's weight and riding style.",
    features: ["Twin-tube cavitation-free damping", "Independent compression / rebound adj.", "Length & preload adjustable", "Bike-specific spring rates", "Two-year warranty", "Available for most liter-class superbikes"],
    price: 425000,
    sku: "OH-TTX-GP",
    tag: "SUSPENSION",
    inStock: false,
  },
  {
    slug: "akrapovi-slip-on-titanium",
    order: 4,
    title: "Akrapovič Slip-On Titanium",
    category: "Exhausts",
    icon: "exhaust",
    brand: "Akrapovič",
    shortDescription: "Hand-welded titanium slip-on with carbon end-cap. Lighter weight, deeper note, gain at the top end.",
    description: "Hand-TIG-welded titanium muffler with woven carbon fibre end cap. Cuts ~3 kg vs OEM. Deeper, fuller note across the rev range and a measurable top-end gain on the dyno. Approved for road use with the removable DB-killer fitted.",
    features: ["Titanium body, carbon end-cap", "TIG-welded by hand in Slovenia", "~3 kg weight saving", "Removable DB-killer included", "Mounting hardware in stainless", "Bike-specific fitment"],
    price: 295000,
    sku: "AK-SO-Ti",
    tag: "EXHAUST",
    inStock: true,
    featured: true,
  },
  {
    slug: "motul-300v-factory-line-10w-40",
    order: 5,
    title: "Motul 300V Factory Line 10W-40",
    category: "Oils",
    icon: "oil",
    brand: "Motul",
    shortDescription: "Ester-based full synthetic. 4-litre service pack for inline-4 sportbikes and naked bikes.",
    description: "The benchmark race oil for four-stroke motorcycles. ESTER Core technology provides maximum film strength under racing conditions. Used as factory fill by multiple WSBK teams. The 4-litre pack is the standard service quantity for most liter-class engines.",
    features: ["100% ester-based full synthetic", "10W-40 viscosity", "API SN / JASO MA2", "4 litre pack", "Factory race-team approved", "Made in France"],
    price: 18900,
    sku: "MT-300V-10W40",
    tag: "FLUID",
    inStock: true,
  },
  {
    slug: "brembo-stylema-calipers",
    order: 6,
    title: "Brembo Stylema Calipers",
    category: "Brakes",
    icon: "disc",
    brand: "Brembo",
    shortDescription: "Forged monobloc front caliper pair. Improved ventilation, sharper bite, race-derived feel.",
    description: "The Stylema is Brembo's evolution of the M50. Improved ventilation channels around each pad, 100 mm radial mount spacing, forged-aluminium monobloc. ~70 g lighter per caliper than the M50. Bite, modulation and feel that's nearly impossible to over-brake with.",
    features: ["Forged monobloc construction", "100 mm radial mount", "Improved pad ventilation", "Approx 70 g lighter than M50", "Race-derived from MotoGP", "Sold as pair, mounting hardware included"],
    price: 385000,
    sku: "BR-STY-100",
    tag: "BRAKE",
    inStock: true,
    featured: true,
  },
  {
    slug: "alpinestars-gp-pro-v2-suit",
    order: 7,
    title: "Alpinestars GP Pro V2 Suit",
    category: "Gear",
    icon: "suit",
    brand: "Alpinestars",
    shortDescription: "Race-spec 1-piece leather suit with full armour and aero hump. Available in custom sizing.",
    description: "A track-ready one-piece in full-grain cowhide leather. Pre-curved arms and legs. Localised stretch panels. Integrated aerodynamic hump. Compatible with Tech-Air airbag system. CE Level 2 armour at shoulders, elbows, knees. Custom sizing available on order.",
    features: ["Full-grain cowhide leather", "CE Level 2 armour throughout", "Aero hump (Tech-Air compatible)", "Pre-curved race fit", "Localised stretch panels", "Removable inner liner"],
    price: 320000,
    sku: "AS-GPPRO-V2",
    tag: "GEAR",
    inStock: true,
  },
  {
    slug: "did-525-zvm-x-gold-chain",
    order: 8,
    title: "DID 525 ZVM-X Gold Chain",
    category: "Chains",
    icon: "chain",
    brand: "DID",
    shortDescription: "X-ring chain rated for liter-class power. Premium gold finish. Includes rivet master link.",
    description: "DID's flagship 525-pitch chain. X-ring seals provide superior longevity vs O-ring. Rated for 200+ horsepower. Gold-on-gold finish. Comes pre-cut for most superbikes with a rivet master link.",
    features: ["X-ring sealed", "525 pitch", "Rated for 200+ hp", "Gold-on-gold premium finish", "Pre-cut to standard lengths", "Rivet master link included"],
    price: 32500,
    sku: "DID-525-ZVMX",
    tag: "CHAIN",
    inStock: true,
  },
];

export const fallbackPosts: Post[] = [
  {
    slug: "why-we-painted-a-mural-inside-our-workshop",
    order: 1,
    title: "Why we painted a mural inside our workshop",
    excerpt: "A 4-metre WSBK tribute on the back wall. The story behind the brush, the bike, and the brand soul.",
    category: "Garage Updates",
    publishedAt: "2025-11-17",
    readTime: "7 min read",
    author: "The Bike House Crew",
    authorRole: "Workshop Team",
    image: "/img/mural-rider.jpg",
    body: postBodies["why-we-painted-a-mural-inside-our-workshop"],
    featured: true,
  },
  {
    slug: "reading-a-bmw-s1000rr-like-a-doctor-reads-an-ekg",
    order: 2,
    title: "Reading a BMW S1000RR like a doctor reads an EKG",
    excerpt: "What live ECU data tells you about ride-by-wire issues — and why dealer scanners aren't always enough.",
    category: "Diagnostics",
    publishedAt: "2025-11-01",
    readTime: "9 min read",
    author: "The Bike House Crew",
    authorRole: "Workshop Team",
    image: "/img/diagnostic-work.jpg",
    body: postBodies["reading-a-bmw-s1000rr-like-a-doctor-reads-an-ekg"],
  },
  {
    slug: "honda-crf250-full-supermoto-conversion",
    order: 3,
    title: "Honda CRF250 → full supermoto conversion",
    excerpt: "17-inch wheels, sticky rubber, sharper geometry. A build diary of one of our favourite customer projects.",
    category: "Builds",
    publishedAt: "2025-10-24",
    readTime: "6 min read",
    author: "The Bike House Crew",
    authorRole: "Workshop Team",
    image: "/img/red-supermoto.jpg",
    body: postBodies["honda-crf250-full-supermoto-conversion"],
  },
  {
    slug: "ducati-desmo-valve-service-what-it-actually-costs",
    order: 4,
    title: "Ducati desmo valve service: what it actually costs",
    excerpt: "Demystifying the dreaded 24,000 km valve check. Time, parts, and how to know you're getting it right.",
    category: "Maintenance",
    publishedAt: "2025-10-11",
    readTime: "8 min read",
    author: "The Bike House Crew",
    authorRole: "Workshop Team",
    image: "/img/ducati-hyper.jpg",
    body: postBodies["ducati-desmo-valve-service-what-it-actually-costs"],
  },
  {
    slug: "liter-bike-touring-kits-bags-screens-ergonomics",
    order: 5,
    title: "Liter-bike touring kits: bags, screens, ergonomics",
    excerpt: "Yes, you can tour on a 1000RR. Here's the kit list we recommend for 500+ km weekend runs.",
    category: "Touring",
    publishedAt: "2025-09-27",
    readTime: "5 min read",
    author: "The Bike House Crew",
    authorRole: "Workshop Team",
    image: "/img/cbr1000rr-front.jpg",
    body: postBodies["liter-bike-touring-kits-bags-screens-ergonomics"],
  },
  {
    slug: "sri-lanka-s-best-b-roads-for-a-sunday-wr-session",
    order: 6,
    title: "Sri Lanka's best B-roads for a Sunday WR session",
    excerpt: "Six routes within 90 minutes of Colombo. Tarmac quality, fuel stops, and the corners we like most.",
    category: "Riding Culture",
    publishedAt: "2025-09-13",
    readTime: "4 min read",
    author: "The Bike House Crew",
    authorRole: "Workshop Team",
    image: "/img/yellow-wr.jpg",
    body: postBodies["sri-lanka-s-best-b-roads-for-a-sunday-wr-session"],
  },
];

export const fallbackTestimonials: Testimonial[] = [
  {
    slug: "dilshan-w",
    order: 1,
    name: "Dilshan W.",
    role: "Owner · BMW S1000RR",
    quote: "I tried three workshops before this one. Bike House diagnosed an electronic gremlin in 40 minutes that two others couldn't find in three weeks. Honest, fast, properly equipped.",
    rating: 5,
    featured: true,
  },
  {
    slug: "roshani-p",
    order: 2,
    name: "Roshani P.",
    role: "Owner · Yamaha MT-09",
    quote: "They tuned my MT-09 for our Nuwara Eliya runs and it transformed the bike. Throttle response is night-and-day. Got photos at every stage of the work.",
    rating: 5,
    featured: true,
  },
  {
    slug: "asanka-f",
    order: 3,
    name: "Asanka F.",
    role: "Owner · Ducati Panigale",
    quote: "The desmo service was less stressful here than the dealership. Real expertise, fair pricing, and they actually called me back about parts ETA. Five years a customer.",
    rating: 5,
    featured: true,
  },
];
